# Generated by Django 5.2 on 2025-09-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='package_images/')),
            ],
        ),
    ]
