# Generated by Django 5.2 on 2025-09-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner', '0002_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='description',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='packages',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
